services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounting-app
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
    ports:
      - "8034:8080"